// AUTO-GENERATED by scripts/generate-reference-banks.js
// Source: fd_rates database, v_latest_rates view
// Regenerate: node scripts/generate-reference-banks.js
// Do not edit by hand.

const REFERENCE_BANKS = {
  Axis: {
    name: 'Axis',
    peakRate: 6.6,
    rates: {
      '7 Days - 90 Days': 5.25,
      '91 Days - 365 Days': 6.0,
      '366 Days - 730 Days': 6.6,
      '731 Days - 1095 Days': 6.6,
      '1096 Days - 1825 Days': 6.6,
    },
  },
  Federal: {
    name: 'Federal',
    peakRate: 6.8,
    rates: {
      '7 Days - 90 Days': 4.25,
      '91 Days - 365 Days': 6.25,
      '366 Days - 730 Days': 6.8,
      '731 Days - 1095 Days': 6.75,
      '1096 Days - 1825 Days': 6.5,
    },
  },
  HDFC: {
    name: 'HDFC',
    peakRate: 6.5,
    rates: {
      '7 Days - 90 Days': 4.5,
      '91 Days - 365 Days': 6.0,
      '366 Days - 730 Days': 6.25,
      '731 Days - 1095 Days': 6.5,
      '1096 Days - 1825 Days': 6.4,
    },
  },
  ICICI: {
    name: 'ICICI',
    peakRate: 6.5,
    rates: {
      '7 Days - 90 Days': 4.0,
      '91 Days - 365 Days': 5.5,
      '366 Days - 730 Days': 6.3,
      '731 Days - 1095 Days': 6.45,
      '1096 Days - 1825 Days': 6.5,
    },
  },
  IDFC: {
    name: 'IDFC',
    peakRate: 7.25,
    rates: {
      '7 Days - 90 Days': 4.5,
      '91 Days - 365 Days': 6.5,
      '366 Days - 730 Days': 7.0,
      '731 Days - 1095 Days': 7.25,
      '1096 Days - 1825 Days': 7.25,
    },
  },
  IOB: {
    name: 'IOB',
    peakRate: 6.6,
    rates: {
      '7 Days - 90 Days': 4.0,
      '91 Days - 365 Days': 6.5,
      '366 Days - 730 Days': 6.6,
      '731 Days - 1095 Days': 6.4,
      '1096 Days - 1825 Days': 0.0,
    },
  },
  IndusInd: {
    name: 'IndusInd',
    peakRate: 7.0,
    rates: {
      '7 Days - 90 Days': 5.8,
      '91 Days - 365 Days': 6.6,
      '366 Days - 730 Days': 7.0,
      '731 Days - 1095 Days': 7.0,
      '1096 Days - 1825 Days': 6.65,
    },
  },
  Kotak: {
    name: 'Kotak',
    peakRate: 6.8,
    rates: {
      '7 Days - 90 Days': 3.5,
      '91 Days - 365 Days': 6.0,
      '366 Days - 730 Days': 6.7,
      '731 Days - 1095 Days': 6.8,
      '1096 Days - 1825 Days': 6.4,
    },
  },
  PNB: {
    name: 'PNB',
    peakRate: 6.6,
    rates: {
      '7 Days - 90 Days': 4.5,
      '91 Days - 365 Days': 6.25,
      '366 Days - 730 Days': 6.6,
      '731 Days - 1095 Days': 6.05,
      '1096 Days - 1825 Days': 6.35,
    },
  },
  SBI: {
    name: 'SBI',
    peakRate: 6.8,
    rates: {
      '7 Days - 90 Days': 3.05,
      '91 Days - 365 Days': 6.55,
      '366 Days - 730 Days': 6.8,
      '731 Days - 1095 Days': 6.45,
      '1096 Days - 1825 Days': 6.3,
    },
  },
  SIB: {
    name: 'SIB',
    peakRate: 7.0,
    rates: {
      '7 Days - 90 Days': 3.5,
      '91 Days - 365 Days': 6.45,
      '366 Days - 730 Days': 6.6,
      '731 Days - 1095 Days': 7.0,
      '1096 Days - 1825 Days': 6.2,
    },
  },
  Yes: {
    name: 'Yes',
    peakRate: 7.25,
    rates: {
      '7 Days - 90 Days': 4.5,
      '91 Days - 365 Days': 6.65,
      '366 Days - 730 Days': 7.25,
      '731 Days - 1095 Days': 7.0,
      '1096 Days - 1825 Days': 7.0,
    },
  }
};

module.exports = { REFERENCE_BANKS };
